version: '3'

services:
    anonymousoverflow:
        container_name: 'anonymousoverflow'
        image: 'ghcr.io/httpjamesm/anonymousoverflow:release'
        env_file:
            - stack.env
        environment:
            - APP_URL=${APP_URL}
            - JWT_SIGNING_SECRET=${JWT_SIGNING_SECRET}
        ports:
            - '9234:8080'
        restart: 'always'

networks:
  default:
    external: true
    name: npm
